## Ćw1. PyTorch Zadania

### 1. Czytanie dokumentacji 

Dużą częścią głębokiego uczenia się (i ogólnie nauki kodowania) jest zapoznanie się z dokumentacją określonego frameworka. Będziemy często korzystać z dokumentacji PyTorch. Poświęć 10 minut na przeczytanie poniższych informacji:
  * Dokumentacja na temat [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * Dokumentacja [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).

### 2. Utwórz losowy tensor o kształcie `(7, 7)`.

In [2]:
# Zaimportuj torch


# Utwórz losowy tensor


### 3. Wykonaj mnożenie macierzowe na tensorze z punktu 2 z innym losowym tensorem o kształcie `(1, 7)` (wskazówka: może być konieczna transpozycja drugiego tensora).

In [4]:
# Utwórz kolejny losowy tensor

# Wykonaj mnożenie macierzowe

### 4. Ustaw losowe ziarno na `0` i wykonaj 2 i 3 od nowa.

Wynik powinien być następujący:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [1]:
# Ustaw ręczne ziarno


# Utwórz dwa losowe tensory


# Mnożenie tensorów przez macierz

### 5. Wiemy, jak ustawić je za pomocą `torch.manual_seed()`, ale czy istnieje odpowiednik GPU? (wskazówka: zajrzyj do dokumentacji dla `torch.cuda`)
  * Jeśli tak, ustaw losowe ziarno GPU na `1234`.

In [1]:
# Ustaw losowe ziarno na GPU



### 6. Utwórz dwa losowe tenosry o kształcie `(2, 3)` i wyślij  do GPU (będzie potrzebny  dostęp do GPU). Ustaw `torch.manual_seed(1234)` podczas tworzenia tensorów (nie musi to być losowe ziarno GPU). Wynik powinien wyglądać mniej więcej tak:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [4]:
# Ustaw losowe ziarno 


# Sprawdź dostęp do GPU


# Utwórz dwa losowe tensory na GPU



### 7. Wykonaj mnożenie macierzy na tensorach utworzonych w punkcie 6 (ponownie może być konieczne dostosowanie kształtu jednego z tensorów).

Wynik powinien wyglądać następująco:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [5]:
# Wykonaj matmul na tensor_A and tensor_B


### 8. Znajdź maximum i minimum wyników 7.

In [3]:
# Wyznacz max

# Wyznacz min


### 9. Znajdź maksymalną i minimalną wartość indeksu wyniku 7.

In [6]:
# Wyznacz arg max


# Wyznacz arg min



### 10. Utwórz losowy tensor o kształcie `(1, 1, 1, 10)`, a następnie utwórz nowy tensor z usuniętymi wszystkimi wymiarami `1`, aby otrzymać tensor o kształcie `(10)`. Ustaw ziarno na `7` podczas tworzenia i wypisz pierwszy tensor i jego kształt, a także drugi tensor i jego kształt.

Wynik powinien być:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [7]:
# Ustaw ziarno


# Utwórz losowy tensor


# Usuń pojedynczy wymiar


# Wydrukuj tensory i ich kształty
