In [1]:
import numpy as np
import torch
import torch.nn as nn

seed = 1337

torch.manual_seed(seed)
torch.cuda.manual_seed_all(seed)
np.random.seed(seed)

%matplotlib inline

### Wykład 2

### Przykład 1

In [2]:
softmax = nn.Softmax(dim=1)
x_input = torch.randn(1, 3)
y_output = softmax(x_input)
print(x_input)
print(y_output)
print(torch.sum(y_output, dim=1))

tensor([[-2.0260, -2.0655, -1.2054]])
tensor([[0.2362, 0.2271, 0.5367]])
tensor([1.])


### Przykład 2

In [3]:
import torch
import torch.nn as nn

mse_loss = nn.MSELoss()
outputs = torch.randn(2, 2, requires_grad=True)
targets = torch.randn(2, 2)
outputs

tensor([[-0.9122, -1.2502],
        [ 0.8032, -0.2071]], requires_grad=True)

In [4]:
targets

tensor([[ 0.0544,  0.1378],
        [-0.3889,  0.5133]])

In [5]:
loss = mse_loss(outputs, targets)
loss.backward()
print(loss)

tensor(1.2003, grad_fn=<MseLossBackward0>)


In [6]:
outputs-targets

tensor([[-0.9666, -1.3881],
        [ 1.1921, -0.7204]], grad_fn=<SubBackward0>)

In [7]:
a=(outputs-targets)*(outputs-targets)
a

tensor([[0.9344, 1.9267],
        [1.4212, 0.5190]], grad_fn=<MulBackward0>)

In [8]:
torch.sum(a)

tensor(4.8014, grad_fn=<SumBackward0>)

In [9]:
torch.mean(a)

tensor(1.2003, grad_fn=<MeanBackward0>)

### Przykład 3

In [10]:
import torch
import torch.nn as nn

ce_loss = nn.CrossEntropyLoss()
outputs = torch.randn(3, 3, requires_grad=True) #liczba kolumn odpowiada liczbie klas
targets = torch.tensor([1, 0, 2], dtype=torch.int64) #mamy 3 klasy
outputs

tensor([[ 0.3319,  0.6300,  0.5815],
        [-0.0282, -0.1744, -1.2221],
        [ 1.5787,  0.5397,  1.1634]], requires_grad=True)

In [11]:
targets

tensor([1, 0, 2])

In [12]:
loss = ce_loss(outputs, targets)
loss.backward()
print (loss)

tensor(0.9600, grad_fn=<NllLossBackward0>)


In [13]:
import torch
import torch.nn as nn

ce_loss = nn.CrossEntropyLoss()
outputs = torch.randn(3, 5, requires_grad=True)
targets = torch.tensor([1, 0, 3], dtype=torch.int64)#pięć klas indeksowanych 0,1,2,3,4
outputs

tensor([[ 0.6947, -1.2307,  0.6871,  1.1841, -0.2909],
        [ 1.5433,  1.8641,  1.6099,  1.3526, -0.7395],
        [-1.1731,  0.9226,  0.0033,  0.6800, -0.8581]], requires_grad=True)

In [14]:
loss = ce_loss(outputs, targets)
loss.backward()
print (loss)

tensor(1.9905, grad_fn=<NllLossBackward0>)


### Przykład 4

In [15]:
bce_loss = nn.BCELoss()
sigmoid = nn.Sigmoid()
probabilities = sigmoid(torch.randn(4, 1, requires_grad=True))
print(probabilities)

targets = torch.tensor([1, 0, 1, 0], dtype=torch.float32).view(4, 1)
loss = bce_loss(probabilities, targets)
loss.backward()
print(loss)

tensor([[0.5774],
        [0.3046],
        [0.4984],
        [0.3039]], grad_fn=<SigmoidBackward0>)
tensor(0.4928, grad_fn=<BinaryCrossEntropyBackward0>)
