In [9]:
import torch
from torch import nn

# Importowanie torchvision
import torchvision
from torchvision import datasets
from torchvision.transforms import ToTensor

random_tensor = torch.randn(size=(1, 1, 2, 2))
print(f"Losowy tensor:\n{random_tensor}")
print(f"Kształt losowego tensor: {random_tensor.shape}")

# Utwórz warstwę max pool layer
max_pool_layer = nn.MaxPool2d(kernel_size=2) # zobacz, co się stanie, gdy zmienisz wartość kernel_size

# Przekazanie losowego tensora przez warstwę max pool
max_pool_tensor = max_pool_layer(random_tensor)
print(f"\nMax pool tensor:\n{max_pool_tensor} <- jest to maksymalna wartość z random_tensor")
print(f"Kształt tensora max_pool: {max_pool_tensor.shape}")

Losowy tensor:
tensor([[[[-0.3772, -0.1485],
          [ 1.7642, -0.8967]]]])
Kształt losowego tensor: torch.Size([1, 1, 2, 2])

Max pool tensor:
tensor([[[[1.7642]]]]) <- jest to maksymalna wartość z random_tensor
Kształt tensora max_pool: torch.Size([1, 1, 1, 1])


In [10]:
tensorA = ([[[[0, 0, 1, 1, 0, 0], [0, 1, 0, 0, 1, 0], [1, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 1], [0, 1, 0, 0, 1, 0], [0, 0, 1, 1, 0, 0]]]])
tensorA = torch.tensor(tensorA)
print(f"tensorA:\n{tensorA}")
print(f"Kształt TensoraA: {tensorA.shape}")
print(f"Typ danych: {tensorA.dtype}")

# Utwórz warstwę max pool layer
max_pool_layer = nn.MaxPool2d(kernel_size=2,stride=1)

# Przekazanie  tensoraA przez warstwę max pool
max_pool_tensor = max_pool_layer(tensorA)
print(f"\nTesnorA po max_pool\n{max_pool_tensor} <- jest to maksymalna wartość z tensorA")
print(f"Kształt tensoraA po max_pool: {max_pool_tensor.shape}")

tensorA:
tensor([[[[0, 0, 1, 1, 0, 0],
          [0, 1, 0, 0, 1, 0],
          [1, 0, 0, 0, 0, 1],
          [1, 0, 0, 0, 0, 1],
          [0, 1, 0, 0, 1, 0],
          [0, 0, 1, 1, 0, 0]]]])
Kształt TensoraA: torch.Size([1, 1, 6, 6])
Typ danych: torch.int64

TesnorA po max_pool
tensor([[[[1, 1, 1, 1, 1],
          [1, 1, 0, 1, 1],
          [1, 0, 0, 0, 1],
          [1, 1, 0, 1, 1],
          [1, 1, 1, 1, 1]]]]) <- jest to maksymalna wartość z tensorA
Kształt tensoraA po max_pool: torch.Size([1, 1, 5, 5])


In [11]:
conv_layer = nn.Conv2d(in_channels=1,
                       out_channels=1,
                       kernel_size=3,
                       stride=1,
                       padding=0)
# Przekazanie danych przez warstwę konwolucyjną
conv_layer(tensorA.float())

tensor([[[[-0.4618, -0.2953, -0.2786, -0.4076],
          [-0.1938, -0.2540, -0.3305, -0.2760],
          [-0.1902, -0.2290, -0.2514, -0.3266],
          [-0.4076, -0.1876, -0.2251, -0.4618]]]],
       grad_fn=<ConvolutionBackward0>)

In [12]:
max_pool_tensor = max_pool_layer(conv_layer(tensorA.float()))
max_pool_tensor


tensor([[[[-0.1938, -0.2540, -0.2760],
          [-0.1902, -0.2290, -0.2514],
          [-0.1876, -0.1876, -0.2251]]]],
       grad_fn=<MaxPool2DWithIndicesBackward0>)